name: Pull Request

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: ./node/ci.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
